sudo: true
dist: trusty
services:
  - docker
language: python
python:
  - '3.5'
before_install:
  - "pip install 'lander>=0.1.0,<0.2'"
script:
  # Compile PDF using containerized lsst-texmf
  - "docker run --rm -v `pwd`:/workspace -w /workspace lsstsqre/lsst-texmf:latest sh -c 'make'"
  # Deploy website. See https://github.com/lsst-sqre/lander for CLI options
  - "lander --pdf LDM-152.pdf --upload --lsstdoc LDM-152.tex --env=travis --ltd-product $PRODUCT"
env:
  global:
    - PRODUCT="ldm-152"
    # Add LSST the Docs credentials
    - secure: "IaGDBgWixI+UZWlqyVeLUZseZJAnWSEzQT0Zyg/Dfzx5qljOL4hAOZ7E0qGcRGarZGe6SSDVODc2nqSN8Nv1OSkDuwDvDkbPzfxElPyQdOHyDg8OlfVMvb4dAm/+306+v8qLzqtTAOo1G7IrqYZrlO2tyxFOiBf3VIXZeXjl3JKOVylcuqs3yEV0w8Rw6pspbCLvwYp1RxQHDqO/loD2j4a4SUf47mm7J22fwSHapENtMXp3ZsDZFBnnKzgvn4Tbd/XphvEIf7S4EFXGaBdZm5Q/meFtFBqF7X16pLSvNcSSubd91/PyWs/dgJ6/IPH5ZjS/dZ0/4/+3ZOn+7iVvtyFkXoDJqf0g9af8zvWsXi+UWDyH1aXTDL+llzmtVyCYNIe9prUuUKKPfQ2pXo7wmLO7+6dq9ODiV3woXw68Oi1/jyJoCt0/R/DSm+FF+zAaMKW1Btz4cYDP7fiUU4FX/cTAbWDbeXTFLiBwso1bByk7BnSqrOJwkhdnz3AvphYcWdBZemxoUqETAwUiYPBNEefSrC0QYTQi5l8p8FqwUU4Uwd+fOMFv+cv4Gos/cu/q++OwxV6mVbVhKxgQcO4I3zgY2BQLj+ZH/BH8ECNaAUWXEoC0eiFllUf5ue99+neLUt2sTSKUBOwaXNgyU6ISRy+qvJQpFDpZf2h7Axr7CdE="
    - secure: "B+CafvZAqjdGh3pgofRBCg0rUTEZiXwQL2ATU6mGFtBkSlZ3TkNPjPeYsiUpMaV8TYuf40bwpipj+z7MnFHGiDoI1dVKkQRxRF1thxfX49N5ZqhSKAXhsr6eSYd5F6bZGaQH5Qc0hS65X3SILFEQ6o3Y7yL8o0JY7Vkaqq72D20UCaVtAmThRS+yy2eM8N3QjmErpTnXza9MlVwJ6esvSyIwiElsbT0dLJiGvFstLZP2NBh9vQIdtXVHlAfO9tY0t+cAK4Kb2piXoX13bRRsDuys842EL6ja/3qb+kxeFpmDgpfZrnnB741LnxwVFYQ5BDli3CM7iJbkExAqJfrewRot6idwU4VTgIN0E0hnRecg64yk5aFeP0T6fHjpMePUA4KUqRd35jastzWfJcNGRShv6o2sRXe7Aw+210bAS6Hdxc/96kFjtLd6WByg93IX7oS4Xzp85Bnlr7Pd1mm3vgYkC6ehQnaP4Zqz9Lt6tzSQ18v8r/ku+oownfJmyMNdrqxNaGnIFiN8azgqNYFFEr5PzwUYO1NP1EwtXfegDQm5v+gAnraTc3YWgSBf2Qt0PWobNvvLv5S/Ln93TJ6V5Kuhz7887xtycCxG/wCZ9eAsgLLY6gjcaSYN3uuJBoI8X9fmaw5PCyaJd7W3CQkjlT0ivhwHEafse1Lg7Ll8Szw="
